# AutoCraft Configuration File
# By dmulloy2

# Weapon Cooldown Time (seconds)
weaponCooldownTime: 6

# Amount of TNT to fire/drop (integer)
numTntToFireNormal: 4
numTntToFireTorpedo: 8
numTntToDropBomb: 2
numTntToDropNapalm: 4

# Materials Needed (material id/string)
materialsNeededForTorpedo:
- DIAMOND
- FLINT_AND_STEEL

materialsNeededForNapalm:
- SLIME_BALL
- FLINT_AND_STEEL

# Napalm Burn Radius
napalmBurnRadius: 6

# Factions Protection Enabled
factionsProtectionsEnabled: true

# Debug
debug: false