dropsNapalm: false
moveSpeed: 3
dropsBomb: false
minBlocks: 1000
maxNumberOfCannons: 0
maxCannonLength: 3
maxShipDimensions: 120
cannonMaterial: 42
maxBlocks: 6000
ignoreAttachments: false
firesTorpedo: false
allowedBlocks:
- 5
- 17
- 35
- 23
- 20
- 5
- 85
- 89
- 50
- 50
- 55
- 30
- 76
- 75
- 61
- 62
- 93
- 94
- 107
- 116
- 53
- 44
- 85
- 29
- 34
- 68
- 63
- 69
- 70
- 72
- 77
- 143
- 96
- 65
- 51
- 87
- 88
- 144
mainType: 5
firesTnt: false
