dropsNapalm: false
moveSpeed: 3
dropsBomb: false
minBlocks: 1000
needsPermission: false
maxNumberOfCannons: 0
maxCannonLength: 3
maxShipDimensions: 120
maxBlocks: 6000
cannonMaterial: IRON_BLOCK
ignoreAttachments: false
allowedTypes:
- WOOD
- LOG
- WOOL
- DISPENSER
- GLASS
- WOOD
- FENCE
- GLOWSTONE
- TORCH
- TORCH
- REDSTONE_WIRE
- WEB
- REDSTONE_TORCH_ON
- REDSTONE_TORCH_OFF
- FURNACE
- BURNING_FURNACE
- DIODE_BLOCK_OFF
- DIODE_BLOCK_ON
- FENCE_GATE
- ENCHANTMENT_TABLE
- WOOD_STAIRS
- STEP
- FENCE
- PISTON_STICKY_BASE
- PISTON_EXTENSION
- WALL_SIGN
- SIGN_POST
- LEVER
- STONE_PLATE
- WOOD_PLATE
- STONE_BUTTON
- WOOD_BUTTON
- TRAP_DOOR
- LADDER
- FIRE
- NETHERRACK
- SOUL_SAND
- SKULL
firesTorpedo: false
mainType: WOOD
firesTnt: false
version: 3
